### ISSUE TITLE
Error: Forever detected script excited with code: 0

### ISSUE THREAD

**Issue by leecollings** [zapty/forever-service#31] opened 2015-07-03 12:03 UTC
Getting this error when trying to install a service, as well as get status, or remove it.

Can't find anywhere that explains this error, and have even seen other forum posts with similar errors but with codes null, 8, etc.

Can you help identify the problem?

**Comment by arvind-agarwal** [comment] 2015-07-03 12:08
Please provide your environment details, and also command you have used to provision the service, also have you tried this with latest release of forever and forever-service?

**Comment by leecollings** [comment] 2015-07-03 12:10
I'm using a RaspberryPi using Debian (from the Domoticz SD card image).
The command I'm using is `forever-service install -s mqtt.js sky-plus-hd-mqtt` (I have already `cd` to the directory the js file is in).
And I assume I'm using the latest release? There's nothing to upgrade when I do `apt-get`

**Comment by arvind-agarwal** [comment] 2015-07-03 12:13
What is version of forever? Have you npm installed latest forever version? and what version of node it has?

**Comment by leecollings** [comment] 2015-07-03 12:15
Can you help me identify these versions?

**Comment by arvind-agarwal** [comment] 2015-07-03 12:49
`node --version`
`forever --version`

**Comment by arvind-agarwal** [comment] 2015-07-03 12:50
Also where are you getting the above error message?

**Comment by leecollings** [comment] 2015-07-03 12:58
After I use `forever-service install -s mqtt.js sky-plus-hd-mqtt`

**Comment by arvind-agarwal** [comment] 2015-07-03 13:00
can you dump full output here

**Comment by leecollings** [comment] 2015-07-03 13:05
No sorry, when i install the service i get:

    forever-service version 0.5.1

    Platform - Raspbian GNU/Linux 7 (wheezy)
    Could not provision service
    Service is already present

**Comment by leecollings** [comment] 2015-07-03 13:06
But after I run `sudo service sky-plus-hd-mqtt start` (or stop, delete or status) I get the following:

error: Forever detected script exited with code: 0
error: Script restart attempt #1
error: Forever detected script exited with code: 0
error: Script restart attempt #2
error: Forever detected script exited with code: 0
error: Script restart attempt #3

And this just loops

**Comment by arvind-agarwal** [comment] 2015-07-03 13:10
node & forever version?

**Comment by leecollings** [comment] 2015-07-03 13:11
I've already given you those:
Forever: 0.14.2
Node: 0.12.1

**Comment by arvind-agarwal** [comment] 2015-07-03 13:15
http://stackoverflow.com/questions/29276996/node-js-and-forever-exited-with-code-0

**Comment by leecollings** [comment] 2015-07-03 13:16
I have already seen that, I can't see how it applies to me though. Is there nothing you can help with?

**Comment by arvind-agarwal** [comment] 2015-07-03 13:16
Are you able to run your script by just running `forever start mqtt.js`?

**Comment by leecollings** [comment] 2015-07-03 13:16
Mainly, I want to know what the error code means

**Comment by arvind-agarwal** [comment] 2015-07-03 13:17
You will have to open issue in forever github

**Comment by leecollings** [comment] 2015-07-03 13:17
$ forever start mqtt.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: mqtt.js

**Comment by leecollings** [comment] 2015-07-03 13:23
Are you able to tell me where you think the issue is? Whether it's in Forever, or Forever-service, or somewhere else?

**Comment by arvind-agarwal** [comment] 2015-07-03 13:27
It is with forever since forever-service has provisioned the service..

**Comment by leecollings** [comment] 2015-07-03 13:29
Okay, thanks

**Comment by arvind-agarwal** [comment] 2015-07-03 13:31
https://ghost.org/forum/installation/17680-unable-to-keep-ghost-up-and-running-with-forever-or-pm2-error-unable-to-access-ghost-s-content-path/ It could be related to permissions also..

**Comment by leecollings** [comment] 2015-07-03 13:32
I've seen that also. But can you actually tell me what the error code 0 means.....?

**Comment by arvind-agarwal** [comment] 2015-07-03 13:32
As i said i have no idea, just trying to help out. Why dont you open issue in forever also.

**Comment by leecollings** [comment] 2015-07-03 13:50
https://github.com/foreverjs/forever/issues/725 - If you could help with this issue, I'd greatly appreciate it. You might have more knowledge and info to give.

**Comment by arvind-agarwal** [comment] 2015-07-07 14:07
@leecollings were you able to resolve this?

**Comment by leecollings** [comment] 2015-07-07 14:18
Nope, haven't heard anything back from my issue in the Forever script. From
the looks of it, they don't answer hardly any of their issues. The guy who
was helping me in the first place also seems to have gone quiet. So right
now, I'm at a bit of a roadblock.

Regards,

*Lee*

**Comment by arvind-agarwal** [comment] 2015-07-07 14:19
ok, to debug it further please see if you have any logs in /var/log/sky-plus-hd-mqtt.log file. If it is, post it here.

**Comment by leecollings** [comment] 2015-07-07 14:22
No, that log file doesn't exist. However in the /var/log folder I have
another folder called Mosquitto, within that there is a general
mosquitto.log if that's helpful?

Regards,

*Lee*

**Comment by arvind-agarwal** [comment] 2015-07-07 14:30
check you /var/log/messages and see after boot you see any messages related to this service..

**Comment by leecollings** [comment] 2015-07-07 14:36
Jul  7 15:32:11 domoticz domoticz: Domoticz is starting up....
Jul  7 15:32:11 domoticz domoticz: Domoticz running...
Jul  7 15:33:00 domoticz kernel: [   57.809247] w1_master_driver
w1_bus_master1: Family 0 for 00.800000000000.8c is not registered.

(The last message, appears many times through the messages list - Although
this could be because I have test devices set up in Domoticz, that don't
have proper IDs.)
But apart from that, that's the only messages on there.

Regards,

*Lee*

**Comment by arvind-agarwal** [comment] 2015-07-07 14:37
Can you put a console.log test message in your script in the beginning and then check if it generates the /var/log/sky-plus-hd-mqtt.log log file when starting the service.

**Comment by leecollings** [comment] 2015-07-07 14:42
So I added console.log("Test"); at the start of the mqtt.js file, and
attempted to start the service by sudo service sky-plus-hd-mqtt start.

I received the Error code:0 message, and checked the log file, and it still
doesn't exist.

Regards,

*Lee*

**Comment by denniskenny** [comment] 2015-07-27 14:48
I'm running Ghost on RaspberryPi and I'm seeing the same error. I would like to just be able to delete the failing service but 'forever-service' delete fails too.

root@pi:/home/dennis/ghost# forever-service delete ghost
forever-service version 0.5.2

Platform - Raspbian GNU/Linux 7 (wheezy)
Shutting down ghost: error: Forever detected script exited with code: 0
error: Script restart attempt #1
error: Forever detected script exited with code: 0
error: Script restart attempt #2
...

**Comment by arvind-agarwal** [comment] 2015-07-30 05:34
Can you provide a script to replicate this issue in  Centos / Debian?

**Comment by denniskenny** [comment] 2015-08-07 21:07
I'm using Raspbian (3.18.7-v7+ armv7l GNU/Linux) and the script is the GhostJs launch script;
https://github.com/TryGhost/Ghost/blob/master/index.js

**Comment by arvind-agarwal** [comment] 2015-08-10 05:52
@denniskenny are you able to replicate it in Centos / or Debian? I cant debug in Raspbian..

**Comment by denniskenny** [comment] 2015-08-10 13:58
Both  @leecollings and myself are using GhostJs on Raspbian, so it may be specific to that build or app. Let me know if there are further steps or logs I can post here. I'll keep digging.

**Comment by houmark** [comment] 2015-08-23 21:49
I'm also seeing `error: Forever detected script exited with code: 0` but I'm using Amazon Linux AMI. Running latest forever 0.15.1 and latest forever-service 0.5.3. I've made sure that both forever and forever-service are installed globally.

I've tried all kinds of things, and have some 5 apps running on the system, and none of them are able to start as a service.

This is hard to debug, because the only error I get is the one above. I've tried the newish --runAsUser but that did not change anything, same error.

@leecollings @denniskenny have you been able to make this work in any way?

**Comment by houmark** [comment] 2015-08-23 21:53
And just wanted to add that starting any of the 5 apps using forever either using sudo or normally as the ec2-user, starts them and runs overall super stable. 4 of them are Express based apps, the last one is a super simple http test app, that includes the below:

```
var http = require('http');

http.createServer(function (request, response) {
  response.writeHead(200, {'Content-Type': 'text/plain'});
  response.end('testing. . .\n');
}).listen(3000);

console.log('Server running');
```

**Comment by arvind-agarwal** [comment] 2015-08-24 04:58
@houmark how did you install nodejs on Amazon Linux? I am trying to debug this, I have personally 50+ instances in Amazon linux running with forever-service and have never faced this issue. So this is kind of strange, are you able to replicate this issue in a brand new Amazon Linux instance also?

**Comment by houmark** [comment] 2015-08-24 15:39
@arvind-agarwal That's a good question. I've been tweaking everything on the server, but the very first install, including nodejs, was done by a college, so I'm not completely sure. Can you point me to anything I can check for reference? nodejs relies in /usr/local/bin/node - sudo is required for global install (have been looking at adding that folder to the sudoers configuration but haven't done it yet).

**Comment by houmark** [comment] 2015-08-24 16:46
@leecollings Not sure why this one was closed now?

In the meantime I was looking more into our current node installation and it seems like the node source was downloaded to the /home/ec2-user/node and then make install from there to its final location /usr/local/bin/node, as mentioned before. Is there a more recommended way? I also saw a recommendation to install using yum (which is how everything else on the server is installed): `sudo yum install nodejs npm --enablerepo=epel`.

@arvind-agarwal What is your recommended way, so I can try to reinstall node in that way? This will be our first production system on AWS with node.js so we don't have much experience in setting it up. Maybe this use case can help tweak either how forever-service runs or some improved docs on how node should be running on Amazon Linux in order for it to work.

**Comment by houmark** [comment] 2015-08-25 00:49
And here follows some more information about our EC2 install:

node.js is installed using make install after downloading the official source. Version is 0.12.4. `make test` runs and completes all tests with no errors found. The etc/sudoers includes (and has always included) /usr/local/bin so nothing to change here in as I see it.

To me it seems like node.js is installed perfectly fine and should not be the issue here. So then the question goes to what we can look at then? I'm curious to hear how you install node.js on your EC2 instances. I would like to try installing a new isolated fresh instance up, but will be awaiting your feedback before attempting that.

**Comment by arvind-agarwal** [comment] 2015-08-25 05:55
@houmark can you try to run with -e param to specify the path
 -e "PATH=/usr/local/bin:\$PATH".

Look at #28 for sample

**Comment by houmark** [comment] 2015-08-25 06:45
@arvind-agarwal Thanks for you feedback.

Unfortunately I get the same result. The service gets provisioned without problems (it always did), but starting it is a problem:

```
[ec2-user@ip-xxx-xxx-xxx-xxx test]$ sudo forever-service install testing -s /var/www/test/app.js -e "PATH=/usr/local/bin:\$PATH"
forever-service version 0.5.3

Platform - Amazon Linux AMI release 2015.03

testing provisioned successfully

Commands to interact with service testing
Start   - "sudo service testing start"
Stop    - "sudo service testing stop"
Status  - "sudo service testing status"
Restart - "sudo service testing restart"
[ec2-user@ip-xxx-xxx-xxx-xxx test]$ sudo service testing start
error: Forever detected script exited with code: 0
```

I also tried without the -s parameter, but with the same result.

**Comment by arvind-agarwal** [comment] 2015-08-25 06:53
@houmark try one more thing, change directory to /var/www/test directory and than provision the script and see if it has better result

`cd /var/www/test`
`sudo forever-service install testing -s app.js -e "PATH=/usr/local/bin:\$PATH"
`

**Comment by houmark** [comment] 2015-08-25 06:54
Unfortunately that's exactly what I did...

**Comment by houmark** [comment] 2015-08-25 06:54
I will try again, I see you did -s app.js which I did not try specifically.

**Comment by arvind-agarwal** [comment] 2015-08-25 06:55
Do you see anything  in /var/log/testing.log?

**Comment by houmark** [comment] 2015-08-25 07:00
I tried -s app.js and same result, and I don't have that log file anywhere on the filesystem. When I use forever normally it creates logs in /home/ec2-user/.forever with random file names but when I start with forever-service no log file is created.

**Comment by arvind-agarwal** [comment] 2015-08-25 07:02
check your /var/log/messages file and see if you have any relevant logs there when you try to start the service?

**Comment by houmark** [comment] 2015-08-25 07:04
Nothing in there of relevance I'm afraid, only DHCPREQUEST etc.

**Comment by arvind-agarwal** [comment] 2015-08-25 07:11
Can you paste output of

`export FOREVER_ROOT=/root/.forever`
`/usr/local/bin/forever --plain list`

**Comment by houmark** [comment] 2015-08-25 07:16
Hmmm, I did the export, which seems to have done some breaking stuff to my setup.

The output is then:
info:    No forever processes running

I do have 4 processes running when running just `forever` it now also shows no processes running, so maybe I will need to change back to my prior FOREVER_ROOT path? Which I am not sure what is right now...

Can this maybe be something with multiple forever being installed somehow. I cannot outrule that forever was installed non-globally to begin with and then later installed globally. I was looking into that but got away from it again.

**Comment by arvind-agarwal** [comment] 2015-08-25 07:22
FOREVER_ROOT is based on the logged in user, it stores .forever in the home directory. so when you do sudo it goes through different FOREVER_ROOT. You can just do unset FOREVER_ROOT to undo the export. BTW please confirm if you ran these commands after doing `sudo -s`

forever-service runs with specific FOREVER_ROOT to avoid any issues since some time environments differ during boot sequence. 

I didnt see a Starting testing message when you sudo service testing start since before attempting to start the service that message is always printed by forever-service, and just before that message forever-service  runs forever list to get status of any running service. Hence I wanted you to run that command.

**Comment by houmark** [comment] 2015-08-25 07:27
Okay, understood.

I re-ran the last commands now like the below with the same result. Anything else I'm missing? I've always run the service install etc. using sudo as it would complain anyways if I didn't.

```
[ec2-user@ip-xxx-xxx-xxx www]$ cd test/
[ec2-user@ip-xxx-xxx-xxx test]$ sudo -s
[root@ip-xxx-xxx-xxx test]# export FOREVER_ROOT=/root/.forever
[root@ip-xxx-xxx-xxx test]# /usr/local/bin/forever --plain list
info:    No forever processes running
[root@ip-xxx-xxx-xxx test]# whoami
root
[root@ip-xxx-xxx-xxx test]#
```

**Comment by arvind-agarwal** [comment] 2015-08-25 07:51
@houmark Please share content of /etc/init.d/testing file

**Comment by arvind-agarwal** [comment] 2015-08-25 07:54
@houmark also can you share output of the command `whereis forever`

**Comment by houmark** [comment] 2015-08-25 08:00
I'm adding testing4 and testing5 in the bottom of this post (these are the latest 2 test and hence I have to do a new service name every time, this is the ones).

Output of whereis (confirms 2 locations, which is confusing me):
[ec2-user@ip-xxx-xxx-xxx-xxx init.d]$ whereis forever
forever: /usr/bin/forever /usr/local/bin/forever

Hope this is of help, and thanks again for your support on this!

```
#!/bin/bash

#
#       /etc/rc.d/init.d/testing4
#
#       testing4 - Provisioned using forever-service
#
# chkconfig: 2345 90 10
# description: forever-service startup script for node script based service testing4, uses forever to start the service
#


#       CLI node /usr/bin/forever-service install testing4 -e PATH=/usr/local/bin:$PATH
#       Working Directory /var/www/test

#Setup Environment variables (if any)


export PATH=/usr/local/bin:$PATH



# Check if any of $pid (could be plural) are running
LOGFILE="/var/log/testing4.log"

LOCKFILE="/var/lock/subsys/testing4"

# introduce some gaps between restarts and throttle continous restarts
MIN_UPTIME="5000"
SPIN_SLEEP_TIME="2000"

# kill signal: Since default needs to be SIGTERM, it is important that services gracefully shutdown,
# specially if they are doing transactions or other work which should not be interuppted in between
# for exceptional situation where you dont care about abrupt shutdown, SIGKILL should be used
KILL_SIGNAL="SIGTERM"

# Wait time afer with SIGKILL will be sent to the process, in case SIGTERM is not fully finished
# This is required since when we use SIGTERM, some times if there is problem in code, it might take lot of time for process to exit
# or process may never exit, in such siutation we have to forcebly kill it so that shutdown or service restart can be done appropriately
# this wait time is in millisecond
KILLWAITTIME=5000

killtree() {
    local _pid=$1
    local _sig=${2:--TERM}
    kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
...skipping...
        done
        checkpidexists $PID
        if [  $? -eq 0  ]; then
                killtree $PID 9
                echo 'Forced shutdown'
        fi

        rm -f $PIDFILE 2>&1 >/dev/null
        rm -f $LOCKFILE 2>&1 >/dev/null
        return 0

}

status() {
        #this is to ensure forever is able to find out the correct root every time
        export FOREVER_ROOT=/root/.forever


        STATUS=$(/usr/bin/forever /usr/local/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(testing4\)\s.*\)/\2-status:\1/;tx;d;:x')

        if [ -z "$STATUS" ]; then
                echo "testing4 is not running"
                RETVAL=3
        else
                echo $STATUS
                RETVAL=0
        fi
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: <servicename> {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
```

```
#!/bin/bash

#
#       /etc/rc.d/init.d/testing5
#
#       testing5 - Provisioned using forever-service
#
# chkconfig: 2345 90 10
# description: forever-service startup script for node script based service testing5, uses forever to start the service
#


#       CLI node /usr/bin/forever-service install testing5 -s app.js -e PATH=/usr/local/bin:$PATH
#       Working Directory /var/www/test

#Setup Environment variables (if any)


export PATH=/usr/local/bin:$PATH



# Check if any of $pid (could be plural) are running
LOGFILE="/var/log/testing5.log"

LOCKFILE="/var/lock/subsys/testing5"

# introduce some gaps between restarts and throttle continous restarts
MIN_UPTIME="5000"
SPIN_SLEEP_TIME="2000"

# kill signal: Since default needs to be SIGTERM, it is important that services gracefully shutdown,
# specially if they are doing transactions or other work which should not be interuppted in between
# for exceptional situation where you dont care about abrupt shutdown, SIGKILL should be used
KILL_SIGNAL="SIGTERM"

# Wait time afer with SIGKILL will be sent to the process, in case SIGTERM is not fully finished
# This is required since when we use SIGTERM, some times if there is problem in code, it might take lot of time for process to exit
# or process may never exit, in such siutation we have to forcebly kill it so that shutdown or service restart can be done appropriately
# this wait time is in millisecond
KILLWAITTIME=5000

killtree() {
    local _pid=$1
    local _sig=${2:--TERM}
    kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
...skipping...
        done
        checkpidexists $PID
        if [  $? -eq 0  ]; then
                killtree $PID 9
                echo 'Forced shutdown'
        fi

        rm -f $PIDFILE 2>&1 >/dev/null
        rm -f $LOCKFILE 2>&1 >/dev/null
        return 0

}

status() {
        #this is to ensure forever is able to find out the correct root every time
        export FOREVER_ROOT=/root/.forever


        STATUS=$(/usr/bin/forever /usr/local/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(testing5\)\s.*\)/\2-status:\1/;tx;d;:x')

        if [ -z "$STATUS" ]; then
                echo "testing5 is not running"
                RETVAL=3
        else
                echo $STATUS
                RETVAL=0
        fi
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: <servicename> {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
```

**Comment by leecollings** [comment] 2015-08-25 08:02
Hi guys, I closed the case mistakenly as I was trying to find a way to
unsubscribe myself from this issue.

Can anyone advise how I can do that? As I don't want to keep receiving
emails every time there's an update. I don't feel as though I need to be
involved in this issue anymore.

On Tuesday, 25 August 2015, houmark <notifications@github.com> wrote:

> I'm adding testing4 and testing5 in the bottom of this post (these are the
> latest 2 test and hence I have to do a new service name every time, this is
> the ones).
>
> Output of whereis (confirms 2 locations, which is confusing me):
> [ec2-user@ip-xxx-xxx-xxx-xxx init.d]$ whereis forever
> forever: /usr/bin/forever /usr/local/bin/forever
>
> Hope this is of help, and thanks again for your support on this!
>
> #!/bin/bash
>
> #
> #       /etc/rc.d/init.d/testing4
> #
> #       testing4 - Provisioned using forever-service
> #
> # chkconfig: 2345 90 10
> # description: forever-service startup script for node script based service testing4, uses forever to start the service
> #
>
>
> #       CLI node /usr/bin/forever-service install testing4 -e PATH=/usr/local/bin:$PATH
> #       Working Directory /var/www/test
>
> #Setup Environment variables (if any)
>
>
> export PATH=/usr/local/bin:$PATH
>
>
>
> # Check if any of $pid (could be plural) are running
> LOGFILE="/var/log/testing4.log"
>
> LOCKFILE="/var/lock/subsys/testing4"
>
> # introduce some gaps between restarts and throttle continous restarts
> MIN_UPTIME="5000"
> SPIN_SLEEP_TIME="2000"
>
> # kill signal: Since default needs to be SIGTERM, it is important that services gracefully shutdown,
> # specially if they are doing transactions or other work which should not be interuppted in between
> # for exceptional situation where you dont care about abrupt shutdown, SIGKILL should be used
> KILL_SIGNAL="SIGTERM"
>
> # Wait time afer with SIGKILL will be sent to the process, in case SIGTERM is not fully finished
> # This is required since when we use SIGTERM, some times if there is problem in code, it might take lot of time for process to exit
> # or process may never exit, in such siutation we have to forcebly kill it so that shutdown or service restart can be done appropriately
> # this wait time is in millisecond
> KILLWAITTIME=5000
>
> killtree() {
>     local _pid=$1
>     local _sig=${2:--TERM}
>     kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
>     for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
>         killtree ${_child} ${_sig}
>     done
>     kill -${_sig} ${_pid}
> ...skipping...
>         done
>         checkpidexists $PID
>         if [  $? -eq 0  ]; then
>                 killtree $PID 9
>                 echo 'Forced shutdown'
>         fi
>
>         rm -f $PIDFILE 2>&1 >/dev/null
>         rm -f $LOCKFILE 2>&1 >/dev/null
>         return 0
>
> }
>
> status() {
>         #this is to ensure forever is able to find out the correct root every time
>         export FOREVER_ROOT=/root/.forever
>
>
>         STATUS=$(/usr/bin/forever /usr/local/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(testing4\)\s.*\)/\2-status:\1/;tx;d;:x')
>
>         if [ -z "$STATUS" ]; then
>                 echo "testing4 is not running"
>                 RETVAL=3
>         else
>                 echo $STATUS
>                 RETVAL=0
>         fi
>         return $RETVAL
> }
>
> case "$1" in
>     start)
>         start
>         ;;
>     stop)
>         stop
>         ;;
>     status)
>         status
>         ;;
>     restart)
>         stop
>         start
>         ;;
>     *)
>         echo "Usage: <servicename> {start|stop|status|restart}"
>         exit 1
>         ;;
> esac
> exit $?
>
> #!/bin/bash
>
> #
> #       /etc/rc.d/init.d/testing5
> #
> #       testing5 - Provisioned using forever-service
> #
> # chkconfig: 2345 90 10
> # description: forever-service startup script for node script based service testing5, uses forever to start the service
> #
>
>
> #       CLI node /usr/bin/forever-service install testing5 -s app.js -e PATH=/usr/local/bin:$PATH
> #       Working Directory /var/www/test
>
> #Setup Environment variables (if any)
>
>
> export PATH=/usr/local/bin:$PATH
>
>
>
> # Check if any of $pid (could be plural) are running
> LOGFILE="/var/log/testing5.log"
>
> LOCKFILE="/var/lock/subsys/testing5"
>
> # introduce some gaps between restarts and throttle continous restarts
> MIN_UPTIME="5000"
> SPIN_SLEEP_TIME="2000"
>
> # kill signal: Since default needs to be SIGTERM, it is important that services gracefully shutdown,
> # specially if they are doing transactions or other work which should not be interuppted in between
> # for exceptional situation where you dont care about abrupt shutdown, SIGKILL should be used
> KILL_SIGNAL="SIGTERM"
>
> # Wait time afer with SIGKILL will be sent to the process, in case SIGTERM is not fully finished
> # This is required since when we use SIGTERM, some times if there is problem in code, it might take lot of time for process to exit
> # or process may never exit, in such siutation we have to forcebly kill it so that shutdown or service restart can be done appropriately
> # this wait time is in millisecond
> KILLWAITTIME=5000
>
> killtree() {
>     local _pid=$1
>     local _sig=${2:--TERM}
>     kill -stop ${_pid} # needed to stop quickly forking parent from producing children between child killing and parent killing
>     for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
>         killtree ${_child} ${_sig}
>     done
>     kill -${_sig} ${_pid}
> ...skipping...
>         done
>         checkpidexists $PID
>         if [  $? -eq 0  ]; then
>                 killtree $PID 9
>                 echo 'Forced shutdown'
>         fi
>
>         rm -f $PIDFILE 2>&1 >/dev/null
>         rm -f $LOCKFILE 2>&1 >/dev/null
>         return 0
>
> }
>
> status() {
>         #this is to ensure forever is able to find out the correct root every time
>         export FOREVER_ROOT=/root/.forever
>
>
>         STATUS=$(/usr/bin/forever /usr/local/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(testing5\)\s.*\)/\2-status:\1/;tx;d;:x')
>
>         if [ -z "$STATUS" ]; then
>                 echo "testing5 is not running"
>                 RETVAL=3
>         else
>                 echo $STATUS
>                 RETVAL=0
>         fi
>         return $RETVAL
> }
>
> case "$1" in
>     start)
>         start
>         ;;
>     stop)
>         stop
>         ;;
>     status)
>         status
>         ;;
>     restart)
>         stop
>         start
>         ;;
>     *)
>         echo "Usage: <servicename> {start|stop|status|restart}"
>         exit 1
>         ;;
> esac
> exit $?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zapty/forever-service/issues/31#issuecomment-134515337>
> .
>


-- 
Regards,

*Lee*

**Comment by arvind-agarwal** [comment] 2015-08-25 08:14
@leecollings you can click on usubscribe notifications

**Comment by arvind-agarwal** [comment] 2015-08-25 08:16
@houmark i just fixed the issue in 0.5.4 it is due to forever being in multiple directories, so whereis forever is giving multiple paths and that was not handled properly.

Please update to latest forever-service 

and try provisioning a new service. You will have to manually remove /etc/init.d/testing service though.

**Comment by leecollings** [comment] 2015-08-25 08:17
Yeah I did that a few times now and it hasn't stopped it.

On Tuesday, 25 August 2015, Arvind Agarwal <notifications@github.com> wrote:

> @houmark <https://github.com/houmark> i just fixed the issue in 0.5.4 it
> is due to forever being in multiple directories, so whereis forever is
> giving multiple paths and that was not handled properly.
>
> Please update to latest forever-service
>
> and try provisioning a new service. You will have to manually remove
> /etc/init.d/testing service though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zapty/forever-service/issues/31#issuecomment-134518618>
> .
>


-- 
Regards,

*Lee*

**Comment by arvind-agarwal** [comment] 2015-08-25 08:21
@leecollings anyway this should be solved with 0.5.4, it would be great if you can test it in your environment so that i can actually close the issue

**Comment by houmark** [comment] 2015-08-25 08:24
Thank you so much! I can confirm the service is now starting with 0.5.4 and after some sleep I will test with all services that I need running. Probably I should do some cleanup and get rid of the multiple forever installs, but at least now you got this edge case taken care of also :)

Thanks again for you quick work on this, really appreciate it!

**Comment by houmark** [comment] 2015-08-25 08:39
Cleaned up old services and installed 4 services for production - all without any issues. Everything is now running smooth. :+1:

**Closed** 2015-08-25 13:07 UTC
